name: Pack Mod Textures
on:
  push:
    branches: [ master, main ]

jobs:
  pack:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Download Unciv jar
        run: |
          wget -q https://github.com

      - name: Force Clean Old Assets
        run: rm -f game.png game.atlas Atlases.json

      - name: Run Texture Packer
        run: java -jar Unciv.jar --pack-mod .

      - name: Commit and Push packed textures
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Forced rewrite of game.png and game.atlas texture sheets"
          file_pattern: 'game.png game.atlas Atlases.json'
          skip_dirty_check: true
          
